const state={data:null};
const $=id=>document.getElementById(id);
const normalize=s=>String(s??'').trim().toUpperCase();
const money=n=>Number(n??0).toLocaleString('en-US',{maximumFractionDigits:0});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmtDate=s=>{if(!s)return '—';const d=new Date(`${s}T00:00:00`);return Number.isNaN(d.getTime())?esc(s):d.toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric'});};
const reducedMotion=()=>window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
async function loadData(){const r=await fetch('data.json',{cache:'no-store'});if(!r.ok)throw Error('Data source unavailable.');state.data=await r.json();}
function animateNumber(el,value){const final=Number(value);if(!el||!Number.isFinite(final)){if(el)el.textContent='—';return}if(reducedMotion()){el.textContent=money(final);return}const start=performance.now(),duration=480;const frame=now=>{const p=Math.min(1,(now-start)/duration),e=1-Math.pow(1-p,3);el.textContent=money(final*e);if(p<1)requestAnimationFrame(frame)};requestAnimationFrame(frame)}
function animateCount(el,value){if(!el)return;el.textContent=String(Math.max(0,Math.floor(Number(value)||0))).padStart(2,'0')}
function statusPill(status){const p=$('member-status-pill');p.textContent=status||'—';p.dataset.status=normalize(status);}
function renderEarnings(member){const target=$('earnings-list'), weeks=member.weeklyEntries||[];if(!weeks.length){target.innerHTML='<div class="empty-state">No recorded Bond earnings are currently entered for this member.</div>';return}const grouped={};weeks.forEach(a=>(grouped[a.week]??=[]).push(a));target.innerHTML=Object.entries(grouped).map(([week,items],i)=>{const total=items.reduce((s,a)=>s+(Number(a.bonds)||0),0);return `<details class="week-card" ${i===0?'open':''}><summary><span class="week-title">${esc(week)}</span><span class="week-total">WEEK TOTAL <strong>${money(total)} 💴</strong></span></summary><div class="week-entries">${items.map(a=>`<div class="earning-row"><div><div class="earning-type">${esc(a.type||'RECORDED ACTIVITY')}</div><div class="earning-name">${esc(a.name||`Activity ${a.entry}`)}</div><div class="earning-meta">Entry #${esc(a.entry)}${a.date?' · '+fmtDate(a.date):''}</div></div><div class="earning-amount">+${money(a.bonds)} 💴</div></div>`).join('')}</div></details>`}).join('')}
function renderAttendance(member){const a=member.attendance||{}, weeks=a.weeks||[];const ov=$('attendance-overview');ov.innerHTML=`<div class="attendance-stat"><span>PERFECT WEEKLY ATTENDANCE</span><strong>${a.perfectWeeks??0} / ${a.totalWeeks??4}</strong></div><div class="attendance-stat"><span>PERFECT CHRONICLE ATTENDANCE</span><strong>${a.perfectChronicle?'✓':'—'}</strong></div>`;$('attendance-days').innerHTML=weeks.length?weeks.map(w=>`<div class="attendance-week"><span>${esc(w.week)}</span><strong>${w.presentDays}/${w.requiredDays} DAYS</strong><small>${w.days?.map(d=>`${esc(d.label)} ${d.present?'✓':'·'}`).join(' · ')||''}</small><small>${w.perfect?'Perfect attendance':'Attendance recorded'}</small></div>`).join(''):'<div class="empty-state">No attendance entries are currently recorded.</div>';$('attendance-bonus-value').textContent=`+${money(a.bonus||0)} 💴`}
function awardList(id,items,empty){$(id).innerHTML=items.length?items.map(a=>`<article class="award-item"><div class="award-item-top"><span class="award-status">EARNED</span><time>${fmtDate(a.date)}</time></div><h5>${esc(a.name)}</h5></article>`).join(''):`<div class="award-empty">${empty}</div>`}
function renderAwards(member){const all=(state.data.awards||[]).filter(a=>normalize(a.memberId)===normalize(member.id)&&normalize(a.status)==='EARNED');animateCount($('crest-count'),member.crests);animateCount($('medallion-count'),member.medallion);awardList('medallion-list',all.filter(a=>normalize(a.category)==='MEDALLION'),'NO MEDALLIONS RECORDED');awardList('crest-list',all.filter(a=>normalize(a.category)==='CREST'),'NO CRESTS RECORDED');awardList('achievement-list',all.filter(a=>normalize(a.category)==='ACHIEVEMENT'),'NO ACHIEVEMENTS RECORDED')}
function renderTransactions(member){const list=(state.data.transactions||[]).filter(t=>normalize(t.memberId)===normalize(member.id));const target=$('transaction-list');if(!list.length){target.innerHTML='<div class="empty-state">No deductions or purchases are currently recorded.</div>';return}target.innerHTML=list.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(t=>`<div class="transaction-row"><div class="tx-date">${fmtDate(t.date)}</div><div><div class="tx-type">${esc(t.type)}</div><div class="tx-desc">${esc(t.description||'No description')}</div></div><div class="tx-amount">−${money(t.amount)} 💴</div></div>`).join('')}
function renderMonthly(member){const archive=state.data.monthlyArchive?.[member.id]||{};const target=$('monthly-list');const rows=Object.entries(archive).filter(([,v])=>v!==null&&v!==''&&Number(v)!==0);target.innerHTML=rows.length?rows.map(([month,v])=>`<div class="monthly-row"><div><span>${esc(month)}</span><small>FINALIZED MONTHLY RECORD</small></div><strong>${money(v)} 💴</strong></div>`).join(''):'<div class="empty-state">No finalized historical monthly records are currently available.</div>'}
function showMember(m){$('member-name').textContent=m.name||'—';$('member-id-display').textContent=m.id||'—';$('member-rank').textContent=m.rank||'—';$('member-join-date').textContent=fmtDate(m.joinDate);statusPill(m.status);animateNumber($('earned'),m.monthlyEarned);animateNumber($('net-summary'),m.overallNet);animateNumber($('deductions'),m.deductions);renderEarnings(m);renderAttendance(m);renderAwards(m);renderTransactions(m);renderMonthly(m);const account=$('account');account.classList.remove('hidden');account.classList.remove('account-reveal');void account.offsetWidth;account.classList.add('account-reveal');account.scrollIntoView({behavior:reducedMotion()?'auto':'smooth',block:'start'})}
$('lookup-form').addEventListener('submit',e=>{e.preventDefault();const id=normalize($('member-id').value);const m=state.data?.members?.find(x=>normalize(x.id)===id);if(!m){$('account').classList.add('hidden');$('lookup-message').textContent='Member ID not found. Please use your official ELX Member ID.';return}$('lookup-message').textContent='';showMember(m)});
const header=$('site-header');let ticking=false;addEventListener('scroll',()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{header?.classList.toggle('is-scrolled',scrollY>12);ticking=false})},{passive:true});
loadData().catch(err=>{$('lookup-message').textContent='The portal data could not be loaded. Please try again later.';console.error(err)});
  
